#ifndef PSKEL_TESTS_CONF_H
#define PSKEL_TESTS_CONF_H

#define TESTS_WIDTH 200
#define TESTS_HEIGHT 300
#define TESTS_DEPTH 50

#define TESTS_ALIGNED_TILING_WIDTH 50
#define TESTS_UNALIGNED_TILING_WIDTH 70

#define TESTS_ALIGNED_TILING_HEIGHT 100
#define TESTS_UNALIGNED_TILING_HEIGHT 120

#define TESTS_EVEN_ITERATIONS 6
#define TESTS_ODD_ITERATIONS 7

#define TESTS_GPUBlockSize 32
#define TESTS_TBBNumThreads 8
#define TESTS_GPUPartition 0.65

#endif
